services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    volumes:
      - /app/node_modules
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
